# Generated by Django 4.0.3 on 2022-04-07 10:17

from django.db import migrations, models
import queries.models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0002_query_name_alter_query_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='expiration_date',
            field=models.DateTimeField(default=queries.models.expire),
        ),
    ]
