# Generated by Django 4.0.3 on 2022-04-07 10:54

from django.db import migrations, models
import queries.models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0003_query_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='date',
            field=models.DateTimeField(default=queries.models.current_date),
        ),
    ]
